// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verification_tokens.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO email_verification_tokens (token, user_id, email, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING token, user_id, email, expires_at
`

type CreateEmailVerificationTokenParams struct {
	Token     string             `json:"token"`
	UserID    int64              `json:"user_id"`
	Email     string             `json:"email"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken,
		arg.Token,
		arg.UserID,
		arg.Email,
		arg.ExpiresAt,
	)
	var i EmailVerificationToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.Email,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteEmailVerificationToken = `-- name: DeleteEmailVerificationToken :exec
DELETE FROM email_verification_tokens WHERE token = $1
`

func (q *Queries) DeleteEmailVerificationToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationToken, token)
	return err
}

const deleteEmailVerificationTokensForUser = `-- name: DeleteEmailVerificationTokensForUser :exec
DELETE FROM email_verification_tokens WHERE user_id = $1
`

// DeleteEmailVerificationTokensForUser drops every outstanding verification
// token for a user, so requesting a new link (a resend, or a second email
// change before the first was confirmed) invalidates any earlier one.
func (q *Queries) DeleteEmailVerificationTokensForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationTokensForUser, userID)
	return err
}

const getEmailVerificationToken = `-- name: GetEmailVerificationToken :one
SELECT token, user_id, email, expires_at FROM email_verification_tokens WHERE token = $1
`

func (q *Queries) GetEmailVerificationToken(ctx context.Context, token string) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationToken, token)
	var i EmailVerificationToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.Email,
		&i.ExpiresAt,
	)
	return i, err
}
