// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset_tokens.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (token, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token, user_id, expires_at
`

type CreatePasswordResetTokenParams struct {
	Token     string             `json:"token"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.Token, arg.UserID, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(&i.Token, &i.UserID, &i.ExpiresAt)
	return i, err
}

const deletePasswordResetToken = `-- name: DeletePasswordResetToken :exec
DELETE FROM password_reset_tokens WHERE token = $1
`

func (q *Queries) DeletePasswordResetToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deletePasswordResetToken, token)
	return err
}

const deletePasswordResetTokensForUser = `-- name: DeletePasswordResetTokensForUser :exec
DELETE FROM password_reset_tokens WHERE user_id = $1
`

// DeletePasswordResetTokensForUser drops every outstanding reset token for a
// user, so requesting a new link invalidates any earlier one that might have
// been forwarded or left sitting in an inbox.
func (q *Queries) DeletePasswordResetTokensForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deletePasswordResetTokensForUser, userID)
	return err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT token, user_id, expires_at FROM password_reset_tokens WHERE token = $1
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, token)
	var i PasswordResetToken
	err := row.Scan(&i.Token, &i.UserID, &i.ExpiresAt)
	return i, err
}
