// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, expires_at, user_agent)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, expires_at, created_at, user_agent, public_id, previous_id, rotated_at
`

type CreateSessionParams struct {
	ID        string             `json:"id"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UserAgent pgtype.Text        `json:"user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.ExpiresAt,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserAgent,
		&i.PublicID,
		&i.PreviousID,
		&i.RotatedAt,
	)
	return i, err
}

const deleteOtherSessionsForUser = `-- name: DeleteOtherSessionsForUser :exec
DELETE FROM sessions WHERE user_id = $1 AND id <> $2 AND previous_id IS DISTINCT FROM $2
`

type DeleteOtherSessionsForUserParams struct {
	UserID int64  `json:"user_id"`
	ID     string `json:"id"`
}

// DeleteOtherSessionsForUser drops every session of a user except the one
// making the request, so changing a password signs out the other devices
// without logging out the person doing the changing.
func (q *Queries) DeleteOtherSessionsForUser(ctx context.Context, arg DeleteOtherSessionsForUserParams) error {
	_, err := q.db.Exec(ctx, deleteOtherSessionsForUser, arg.UserID, arg.ID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1 OR previous_id = $1
`

// DeleteSession matches the token just replaced as well as the current one,
// so a logout that races a refresh still ends the session.
func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionForUser = `-- name: DeleteSessionForUser :exec
DELETE FROM sessions WHERE public_id = $1 AND user_id = $2
`

type DeleteSessionForUserParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	UserID   int64       `json:"user_id"`
}

// DeleteSessionForUser is the scoped counterpart to DeleteSession: it takes
// a user_id as well as the session's public_id (never its id, which is the
// refresh token and is not sent to clients) so that an id a client sends
// can only ever delete a session owned by the caller.
func (q *Queries) DeleteSessionForUser(ctx context.Context, arg DeleteSessionForUserParams) error {
	_, err := q.db.Exec(ctx, deleteSessionForUser, arg.PublicID, arg.UserID)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions WHERE user_id = $1
`

// DeleteSessionsForUser drops every session of a user, including the one
// making the request. A password reset has no current session to spare --
// the visitor arrived signed out -- so every device gets logged out and the
// freshly reset password is what signs them back in.
func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteSessionsForUser, userID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, expires_at, created_at, user_agent, public_id, previous_id, rotated_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserAgent,
		&i.PublicID,
		&i.PreviousID,
		&i.RotatedAt,
	)
	return i, err
}

const getSessionByPreviousID = `-- name: GetSessionByPreviousID :one
SELECT id, user_id, expires_at, created_at, user_agent, public_id, previous_id, rotated_at FROM sessions WHERE previous_id = $1
`

func (q *Queries) GetSessionByPreviousID(ctx context.Context, previousID pgtype.Text) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByPreviousID, previousID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserAgent,
		&i.PublicID,
		&i.PreviousID,
		&i.RotatedAt,
	)
	return i, err
}

const listSessionsForUser = `-- name: ListSessionsForUser :many
SELECT id, user_id, expires_at, created_at, user_agent, public_id, previous_id, rotated_at FROM sessions WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSessionsForUser(ctx context.Context, userID int64) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UserAgent,
			&i.PublicID,
			&i.PreviousID,
			&i.RotatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateSession = `-- name: RotateSession :one
UPDATE sessions SET previous_id = id, id = $2, rotated_at = now()
WHERE id = $1 AND expires_at > now()
RETURNING id, user_id, expires_at, created_at, user_agent, public_id, previous_id, rotated_at
`

type RotateSessionParams struct {
	ID   string `json:"id"`
	ID_2 string `json:"id_2"`
}

// RotateSession swaps an unexpired session's token for a new one in place, so
// the row (public_id, created_at, user_agent, expires_at) is the same session
// throughout. It matches nothing if the token is unknown, expired or already
// replaced, which is how two refreshes racing on one token are told apart:
// exactly one wins. The right-hand sides read the row as it was before the
// update, so previous_id gets the old token.
func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, rotateSession, arg.ID, arg.ID_2)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserAgent,
		&i.PublicID,
		&i.PreviousID,
		&i.RotatedAt,
	)
	return i, err
}
