// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bank_emails.sql

package sqlcgen

import (
	"context"
)

const countBankEmailsForUser = `-- name: CountBankEmailsForUser :one
SELECT count(*) FROM bank_emails WHERE user_id = $1
`

func (q *Queries) CountBankEmailsForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countBankEmailsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBankEmail = `-- name: CreateBankEmail :one
INSERT INTO bank_emails (user_id, message_id, from_address, subject, body, status, failure_reason)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, message_id) DO NOTHING
RETURNING id, user_id, message_id, from_address, subject, body, received_at, occurred_at, status, failure_reason, processed_at
`

type CreateBankEmailParams struct {
	UserID        int64  `json:"user_id"`
	MessageID     string `json:"message_id"`
	FromAddress   string `json:"from_address"`
	Subject       string `json:"subject"`
	Body          string `json:"body"`
	Status        string `json:"status"`
	FailureReason string `json:"failure_reason"`
}

// CreateBankEmail lưu một thư vừa tới. ON CONFLICT DO NOTHING vì unique index
// trên (user_id, message_id) là thứ chặn thư trùng, và một thư trùng không
// phải lỗi để trả về cho Worker -- Worker không làm gì được với nó.
func (q *Queries) CreateBankEmail(ctx context.Context, arg CreateBankEmailParams) (BankEmail, error) {
	row := q.db.QueryRow(ctx, createBankEmail,
		arg.UserID,
		arg.MessageID,
		arg.FromAddress,
		arg.Subject,
		arg.Body,
		arg.Status,
		arg.FailureReason,
	)
	var i BankEmail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MessageID,
		&i.FromAddress,
		&i.Subject,
		&i.Body,
		&i.ReceivedAt,
		&i.OccurredAt,
		&i.Status,
		&i.FailureReason,
		&i.ProcessedAt,
	)
	return i, err
}

const deleteBankEmailsForUser = `-- name: DeleteBankEmailsForUser :exec
DELETE FROM bank_emails WHERE user_id = $1
`

func (q *Queries) DeleteBankEmailsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteBankEmailsForUser, userID)
	return err
}

const listRecentBankEmails = `-- name: ListRecentBankEmails :many
SELECT id, user_id, message_id, from_address, subject, body, received_at, occurred_at, status, failure_reason, processed_at FROM bank_emails
WHERE user_id = $1
ORDER BY received_at DESC
LIMIT $2
`

type ListRecentBankEmailsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

// ListRecentBankEmails is what the settings card actually shows: the
// owner's most recent forwards regardless of status, so a forwarded email
// shows up right away as 'pending' rather than only appearing once (or if)
// it ever reaches 'failed'.
func (q *Queries) ListRecentBankEmails(ctx context.Context, arg ListRecentBankEmailsParams) ([]BankEmail, error) {
	rows, err := q.db.Query(ctx, listRecentBankEmails, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankEmail
	for rows.Next() {
		var i BankEmail
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MessageID,
			&i.FromAddress,
			&i.Subject,
			&i.Body,
			&i.ReceivedAt,
			&i.OccurredAt,
			&i.Status,
			&i.FailureReason,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentFailedBankEmails = `-- name: ListRecentFailedBankEmails :many
SELECT id, user_id, message_id, from_address, subject, body, received_at, occurred_at, status, failure_reason, processed_at FROM bank_emails
WHERE user_id = $1 AND status = 'failed'
ORDER BY received_at DESC
LIMIT $2
`

type ListRecentFailedBankEmailsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListRecentFailedBankEmails(ctx context.Context, arg ListRecentFailedBankEmailsParams) ([]BankEmail, error) {
	rows, err := q.db.Query(ctx, listRecentFailedBankEmails, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankEmail
	for rows.Next() {
		var i BankEmail
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MessageID,
			&i.FromAddress,
			&i.Subject,
			&i.Body,
			&i.ReceivedAt,
			&i.OccurredAt,
			&i.Status,
			&i.FailureReason,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueFailedBankEmails = `-- name: RequeueFailedBankEmails :exec
UPDATE bank_emails SET status = 'pending', failure_reason = '', processed_at = NULL
WHERE user_id = $1 AND status = 'failed'
`

// RequeueFailedBankEmails là nút "Thử lại": đặt mọi thư failed về pending để
// lượt xử lý sau đọc lại chúng bằng parser đã sửa. Đây là toàn bộ lý do chọn
// phương án lưu email thô.
func (q *Queries) RequeueFailedBankEmails(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, requeueFailedBankEmails, userID)
	return err
}
