// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bank_emails.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingBankEmail = `-- name: ClaimPendingBankEmail :one
UPDATE bank_emails SET status = 'processing'
WHERE id = $1 AND status = 'pending'
RETURNING id, user_id, message_id, from_address, subject, body, received_at, occurred_at, status, failure_reason, processed_at
`

// ClaimPendingBankEmail giành một email pending cho đúng một goroutine: chỉ
// goroutine nào UPDATE trúng dòng còn 'pending' mới nhận được nó về, mọi
// goroutine khác chạy cùng lúc nhận không hàng nào (pgx.ErrNoRows) và phải bỏ
// qua email này. Đọc rồi mới ghi sẽ để hai goroutine cùng xử lý một email và
// tạo hai transaction từ một thư.
func (q *Queries) ClaimPendingBankEmail(ctx context.Context, id int64) (BankEmail, error) {
	row := q.db.QueryRow(ctx, claimPendingBankEmail, id)
	var i BankEmail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MessageID,
		&i.FromAddress,
		&i.Subject,
		&i.Body,
		&i.ReceivedAt,
		&i.OccurredAt,
		&i.Status,
		&i.FailureReason,
		&i.ProcessedAt,
	)
	return i, err
}

const countBankEmailsForUser = `-- name: CountBankEmailsForUser :one
SELECT count(*) FROM bank_emails WHERE user_id = $1
`

func (q *Queries) CountBankEmailsForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countBankEmailsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBankEmail = `-- name: CreateBankEmail :one
INSERT INTO bank_emails (user_id, message_id, from_address, subject, body, raw_body, status, failure_reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id, message_id) DO NOTHING
RETURNING id, user_id, message_id, from_address, subject, body, received_at, occurred_at, status, failure_reason, processed_at, raw_body
`

type CreateBankEmailParams struct {
	UserID        int64  `json:"user_id"`
	MessageID     string `json:"message_id"`
	FromAddress   string `json:"from_address"`
	Subject       string `json:"subject"`
	Body          string `json:"body"`
	RawBody       string `json:"raw_body"`
	Status        string `json:"status"`
	FailureReason string `json:"failure_reason"`
}

// CreateBankEmail lưu một thư vừa tới. ON CONFLICT DO NOTHING vì unique index
// trên (user_id, message_id) là thứ chặn thư trùng, và một thư trùng không
// phải lỗi để trả về cho Worker -- Worker không làm gì được với nó.
func (q *Queries) CreateBankEmail(ctx context.Context, arg CreateBankEmailParams) (BankEmail, error) {
	row := q.db.QueryRow(ctx, createBankEmail,
		arg.UserID,
		arg.MessageID,
		arg.FromAddress,
		arg.Subject,
		arg.Body,
		arg.RawBody,
		arg.Status,
		arg.FailureReason,
	)
	var i BankEmail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MessageID,
		&i.FromAddress,
		&i.Subject,
		&i.Body,
		&i.ReceivedAt,
		&i.OccurredAt,
		&i.Status,
		&i.FailureReason,
		&i.ProcessedAt,
		&i.RawBody,
	)
	return i, err
}

const deleteBankEmailsForUser = `-- name: DeleteBankEmailsForUser :exec
DELETE FROM bank_emails WHERE user_id = $1
`

func (q *Queries) DeleteBankEmailsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteBankEmailsForUser, userID)
	return err
}

const listPendingBankEmailIDs = `-- name: ListPendingBankEmailIDs :many
SELECT id FROM bank_emails
WHERE user_id = $1 AND status = 'pending'
ORDER BY received_at
`

// ListPendingBankEmailIDs is what the processing loop walks: every pending
// email for the user, not just the one that just arrived, so a Render
// restart that left one mid-flight gets swept up by whichever email
// processes next instead of needing a cron job of its own.
func (q *Queries) ListPendingBankEmailIDs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listPendingBankEmailIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentBankEmails = `-- name: ListRecentBankEmails :many
SELECT id, user_id, message_id, from_address, subject, body, received_at, occurred_at, status, failure_reason, processed_at, raw_body FROM bank_emails
WHERE user_id = $1
ORDER BY received_at DESC
LIMIT $2
`

type ListRecentBankEmailsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

// ListRecentBankEmails is what the settings card actually shows: the
// owner's most recent forwards regardless of status, so a forwarded email
// shows up right away as 'pending' rather than only appearing once (or if)
// it ever reaches 'failed'.
func (q *Queries) ListRecentBankEmails(ctx context.Context, arg ListRecentBankEmailsParams) ([]BankEmail, error) {
	rows, err := q.db.Query(ctx, listRecentBankEmails, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankEmail
	for rows.Next() {
		var i BankEmail
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MessageID,
			&i.FromAddress,
			&i.Subject,
			&i.Body,
			&i.ReceivedAt,
			&i.OccurredAt,
			&i.Status,
			&i.FailureReason,
			&i.ProcessedAt,
			&i.RawBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentFailedBankEmails = `-- name: ListRecentFailedBankEmails :many
SELECT id, user_id, message_id, from_address, subject, body, received_at, occurred_at, status, failure_reason, processed_at, raw_body FROM bank_emails
WHERE user_id = $1 AND status = 'failed'
ORDER BY received_at DESC
LIMIT $2
`

type ListRecentFailedBankEmailsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListRecentFailedBankEmails(ctx context.Context, arg ListRecentFailedBankEmailsParams) ([]BankEmail, error) {
	rows, err := q.db.Query(ctx, listRecentFailedBankEmails, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankEmail
	for rows.Next() {
		var i BankEmail
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MessageID,
			&i.FromAddress,
			&i.Subject,
			&i.Body,
			&i.ReceivedAt,
			&i.OccurredAt,
			&i.Status,
			&i.FailureReason,
			&i.ProcessedAt,
			&i.RawBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBankEmailFailed = `-- name: MarkBankEmailFailed :exec
UPDATE bank_emails SET status = 'failed', failure_reason = $2, processed_at = now()
WHERE id = $1
`

type MarkBankEmailFailedParams struct {
	ID            int64  `json:"id"`
	FailureReason string `json:"failure_reason"`
}

// MarkBankEmailFailed is the "needs fixing" list: our own error, not the
// sender's mail. failure_reason is what the retry button on /settings reads
// back, and processed_at records when the read was found bad.
func (q *Queries) MarkBankEmailFailed(ctx context.Context, arg MarkBankEmailFailedParams) error {
	_, err := q.db.Exec(ctx, markBankEmailFailed, arg.ID, arg.FailureReason)
	return err
}

const markBankEmailIgnored = `-- name: MarkBankEmailIgnored :exec
UPDATE bank_emails SET status = 'ignored', failure_reason = $2, processed_at = now()
WHERE id = $1
`

type MarkBankEmailIgnoredParams struct {
	ID            int64  `json:"id"`
	FailureReason string `json:"failure_reason"`
}

// MarkBankEmailIgnored covers an unknown sender or a body that parses to no
// transaction (OTP, ad, a failed transfer). Kept separate from 'failed' so
// that list stays a to-do rather than filling with ordinary bank mail.
func (q *Queries) MarkBankEmailIgnored(ctx context.Context, arg MarkBankEmailIgnoredParams) error {
	_, err := q.db.Exec(ctx, markBankEmailIgnored, arg.ID, arg.FailureReason)
	return err
}

const markBankEmailImported = `-- name: MarkBankEmailImported :exec
UPDATE bank_emails SET status = 'imported', occurred_at = $2, processed_at = now()
WHERE id = $1
`

type MarkBankEmailImportedParams struct {
	ID         int64              `json:"id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

// MarkBankEmailImported closes an email that became a transaction. occurred_at
// keeps the full Notice.OccurredAt timestamp; transactions.occurred_on only
// ever holds the date part of it.
func (q *Queries) MarkBankEmailImported(ctx context.Context, arg MarkBankEmailImportedParams) error {
	_, err := q.db.Exec(ctx, markBankEmailImported, arg.ID, arg.OccurredAt)
	return err
}

const requeueFailedBankEmails = `-- name: RequeueFailedBankEmails :exec
UPDATE bank_emails SET status = 'pending', failure_reason = '', processed_at = NULL
WHERE user_id = $1 AND status = 'failed'
`

// RequeueFailedBankEmails là nút "Thử lại": đặt mọi thư failed về pending để
// lượt xử lý sau đọc lại chúng bằng parser đã sửa. Đây là toàn bộ lý do chọn
// phương án lưu email thô.
func (q *Queries) RequeueFailedBankEmails(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, requeueFailedBankEmails, userID)
	return err
}
