// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bank_accounts.sql

package sqlcgen

import (
	"context"
)

const bankAccountBelongsToUser = `-- name: BankAccountBelongsToUser :one
SELECT EXISTS (
    SELECT 1 FROM bank_accounts WHERE user_id = $1 AND account_number = $2
) AS owns
`

type BankAccountBelongsToUserParams struct {
	UserID        int64  `json:"user_id"`
	AccountNumber string `json:"account_number"`
}

// BankAccountBelongsToUser trả về true khi số tài khoản này đã từng xuất
// hiện ở ô "Tài khoản trích nợ" của chính người dùng đó.
func (q *Queries) BankAccountBelongsToUser(ctx context.Context, arg BankAccountBelongsToUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, bankAccountBelongsToUser, arg.UserID, arg.AccountNumber)
	var owns bool
	err := row.Scan(&owns)
	return owns, err
}

const rememberBankAccount = `-- name: RememberBankAccount :exec
INSERT INTO bank_accounts (user_id, account_number)
VALUES ($1, $2)
ON CONFLICT (user_id, account_number) DO NOTHING
`

type RememberBankAccountParams struct {
	UserID        int64  `json:"user_id"`
	AccountNumber string `json:"account_number"`
}

// RememberBankAccount ghi nhận một số tài khoản là của người dùng. Không lỗi
// khi đã có: mỗi email lặp lại đều gọi hàm này.
func (q *Queries) RememberBankAccount(ctx context.Context, arg RememberBankAccountParams) error {
	_, err := q.db.Exec(ctx, rememberBankAccount, arg.UserID, arg.AccountNumber)
	return err
}
