// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category_hints.sql

package sqlcgen

import (
	"context"
)

const deleteCategoryHintsForUser = `-- name: DeleteCategoryHintsForUser :exec
DELETE FROM category_hints WHERE user_id = $1
`

func (q *Queries) DeleteCategoryHintsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteCategoryHintsForUser, userID)
	return err
}

const getCategoryHint = `-- name: GetCategoryHint :one
SELECT id, user_id, note_key, category_id, updated_at FROM category_hints
WHERE user_id = $1 AND note_key = $2
`

type GetCategoryHintParams struct {
	UserID  int64  `json:"user_id"`
	NoteKey string `json:"note_key"`
}

// GetCategoryHint looks up the remembered category for one user's note_key.
// pgx.ErrNoRows on a miss is not an error condition here -- it is what
// tells the processing loop to fall back to Other/Other income (and, once
// a later slice adds it, to ask the classifier).
func (q *Queries) GetCategoryHint(ctx context.Context, arg GetCategoryHintParams) (CategoryHint, error) {
	row := q.db.QueryRow(ctx, getCategoryHint, arg.UserID, arg.NoteKey)
	var i CategoryHint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NoteKey,
		&i.CategoryID,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCategoryHint = `-- name: UpsertCategoryHint :one
INSERT INTO category_hints (user_id, note_key, category_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, note_key) DO UPDATE
SET category_id = $3, updated_at = now()
RETURNING id, user_id, note_key, category_id, updated_at
`

type UpsertCategoryHintParams struct {
	UserID     int64  `json:"user_id"`
	NoteKey    string `json:"note_key"`
	CategoryID int64  `json:"category_id"`
}

// UpsertCategoryHint is how the memory learns: the processing loop writes
// one the first time a note_key is seen with no hint yet, and a user
// correcting the category on an email-sourced transaction writes one that
// always overwrites whatever was there. ON CONFLICT on (user_id, note_key)
// is what makes the second case an overwrite instead of a second row.
func (q *Queries) UpsertCategoryHint(ctx context.Context, arg UpsertCategoryHintParams) (CategoryHint, error) {
	row := q.db.QueryRow(ctx, upsertCategoryHint, arg.UserID, arg.NoteKey, arg.CategoryID)
	var i CategoryHint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NoteKey,
		&i.CategoryID,
		&i.UpdatedAt,
	)
	return i, err
}
