// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int64              `json:"id"`
	UserID    pgtype.Int8        `json:"user_id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Color     string             `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Slug      pgtype.Text        `json:"slug"`
}

type PasswordResetToken struct {
	Token     string             `json:"token"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Session struct {
	ID        string             `json:"id"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Transaction struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	CategoryID  int64              `json:"category_id"`
	Amount      int64              `json:"amount"`
	Type        string             `json:"type"`
	Description string             `json:"description"`
	OccurredOn  pgtype.Date        `json:"occurred_on"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                  int64              `json:"id"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	Name                string             `json:"name"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	Theme               string             `json:"theme"`
	Username            string             `json:"username"`
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
}
