// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BankEmail struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	MessageID     string             `json:"message_id"`
	FromAddress   string             `json:"from_address"`
	Subject       string             `json:"subject"`
	Body          string             `json:"body"`
	ReceivedAt    pgtype.Timestamptz `json:"received_at"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	Status        string             `json:"status"`
	FailureReason string             `json:"failure_reason"`
	ProcessedAt   pgtype.Timestamptz `json:"processed_at"`
	RawBody       string             `json:"raw_body"`
}

type Category struct {
	ID        int64              `json:"id"`
	UserID    pgtype.Int8        `json:"user_id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Color     string             `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Slug      pgtype.Text        `json:"slug"`
}

type CategoryHint struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	NoteKey    string             `json:"note_key"`
	CategoryID int64              `json:"category_id"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type EmailVerificationToken struct {
	Token     string             `json:"token"`
	UserID    int64              `json:"user_id"`
	Email     string             `json:"email"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type PasswordResetToken struct {
	Token     string             `json:"token"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Session struct {
	ID        string             `json:"id"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserAgent pgtype.Text        `json:"user_agent"`
}

type Transaction struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	CategoryID  int64              `json:"category_id"`
	Amount      int64              `json:"amount"`
	Type        string             `json:"type"`
	Description string             `json:"description"`
	OccurredOn  pgtype.Date        `json:"occurred_on"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Source      string             `json:"source"`
	BankEmailID pgtype.Int8        `json:"bank_email_id"`
}

type User struct {
	ID                  int64              `json:"id"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	Name                string             `json:"name"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	Theme               string             `json:"theme"`
	Username            string             `json:"username"`
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
	EmailVerified       bool               `json:"email_verified"`
	PendingEmail        pgtype.Text        `json:"pending_email"`
	InboxToken          pgtype.Text        `json:"inbox_token"`
}
