// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const categoryBreakdown = `-- name: CategoryBreakdown :many
SELECT c.slug AS category_slug, c.name AS category_name, c.color AS category_color, SUM(t.amount)::bigint AS total
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1 AND t.type = 'expense' AND t.occurred_on >= $2 AND t.occurred_on < $3
GROUP BY c.slug, c.name, c.color
ORDER BY total DESC
`

type CategoryBreakdownParams struct {
	UserID       int64       `json:"user_id"`
	OccurredOn   pgtype.Date `json:"occurred_on"`
	OccurredOn_2 pgtype.Date `json:"occurred_on_2"`
}

type CategoryBreakdownRow struct {
	CategorySlug  pgtype.Text `json:"category_slug"`
	CategoryName  string      `json:"category_name"`
	CategoryColor string      `json:"category_color"`
	Total         int64       `json:"total"`
}

func (q *Queries) CategoryBreakdown(ctx context.Context, arg CategoryBreakdownParams) ([]CategoryBreakdownRow, error) {
	rows, err := q.db.Query(ctx, categoryBreakdown, arg.UserID, arg.OccurredOn, arg.OccurredOn_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryBreakdownRow
	for rows.Next() {
		var i CategoryBreakdownRow
		if err := rows.Scan(
			&i.CategorySlug,
			&i.CategoryName,
			&i.CategoryColor,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTransactionsForCategory = `-- name: CountTransactionsForCategory :one
SELECT COUNT(*)::bigint AS count FROM transactions
WHERE category_id = $1 AND user_id = $2
`

type CountTransactionsForCategoryParams struct {
	CategoryID int64 `json:"category_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) CountTransactionsForCategory(ctx context.Context, arg CountTransactionsForCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsForCategory, arg.CategoryID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsForMonth = `-- name: CountTransactionsForMonth :one
SELECT COUNT(*)::bigint AS count
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1 AND t.occurred_on >= $2 AND t.occurred_on < $3
  AND ($4::text IS NULL
       OR t.description ILIKE '%' || $4::text || '%'
       OR (c.slug IS NULL AND c.name ILIKE '%' || $4::text || '%')
       OR c.slug = ANY($5::text[]))
  AND ($6::text IS NULL OR t.type = $6::text)
  AND ($7::bigint IS NULL OR t.category_id = $7::bigint)
  AND ($8::bigint IS NULL OR t.amount >= $8::bigint)
  AND ($9::bigint IS NULL OR t.amount <= $9::bigint)
`

type CountTransactionsForMonthParams struct {
	UserID       int64       `json:"user_id"`
	OccurredOn   pgtype.Date `json:"occurred_on"`
	OccurredOn_2 pgtype.Date `json:"occurred_on_2"`
	Search       pgtype.Text `json:"search"`
	SearchSlugs  []string    `json:"search_slugs"`
	Type         pgtype.Text `json:"type"`
	CategoryID   pgtype.Int8 `json:"category_id"`
	MinAmount    pgtype.Int8 `json:"min_amount"`
	MaxAmount    pgtype.Int8 `json:"max_amount"`
}

// CountTransactionsForMonth answers how many rows the list above would have,
// and so carries exactly the same filter predicates. Keep the two WHERE
// clauses identical: everything that reads a page -- the pager's page count,
// the count chip, the empty state -- trusts that they agree.
func (q *Queries) CountTransactionsForMonth(ctx context.Context, arg CountTransactionsForMonthParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsForMonth,
		arg.UserID,
		arg.OccurredOn,
		arg.OccurredOn_2,
		arg.Search,
		arg.SearchSlugs,
		arg.Type,
		arg.CategoryID,
		arg.MinAmount,
		arg.MaxAmount,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, category_id, amount, type, description, occurred_on)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, category_id, amount, type, description, occurred_on, created_at, updated_at
`

type CreateTransactionParams struct {
	UserID      int64       `json:"user_id"`
	CategoryID  int64       `json:"category_id"`
	Amount      int64       `json:"amount"`
	Type        string      `json:"type"`
	Description string      `json:"description"`
	OccurredOn  pgtype.Date `json:"occurred_on"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Type,
		arg.Description,
		arg.OccurredOn,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Type,
		&i.Description,
		&i.OccurredOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTransactionsForUser = `-- name: DeleteTransactionsForUser :exec
DELETE FROM transactions WHERE user_id = $1
`

// DeleteTransactionsForUser clears the history an account leaves behind when
// it is deleted. It runs before the categories are removed because
// transactions.category_id has no ON DELETE clause of its own.
func (q *Queries) DeleteTransactionsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteTransactionsForUser, userID)
	return err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, user_id, category_id, amount, type, description, occurred_on, created_at, updated_at FROM transactions WHERE id = $1 AND user_id = $2
`

type GetTransactionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Type,
		&i.Description,
		&i.OccurredOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionWithCategory = `-- name: GetTransactionWithCategory :one
SELECT t.id, t.user_id, t.category_id, t.amount, t.type, t.description, t.occurred_on, t.created_at, t.updated_at, c.slug AS category_slug, c.name AS category_name, c.color AS category_color
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.id = $1 AND t.user_id = $2
`

type GetTransactionWithCategoryParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type GetTransactionWithCategoryRow struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	CategoryID    int64              `json:"category_id"`
	Amount        int64              `json:"amount"`
	Type          string             `json:"type"`
	Description   string             `json:"description"`
	OccurredOn    pgtype.Date        `json:"occurred_on"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CategorySlug  pgtype.Text        `json:"category_slug"`
	CategoryName  string             `json:"category_name"`
	CategoryColor string             `json:"category_color"`
}

func (q *Queries) GetTransactionWithCategory(ctx context.Context, arg GetTransactionWithCategoryParams) (GetTransactionWithCategoryRow, error) {
	row := q.db.QueryRow(ctx, getTransactionWithCategory, arg.ID, arg.UserID)
	var i GetTransactionWithCategoryRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Type,
		&i.Description,
		&i.OccurredOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategorySlug,
		&i.CategoryName,
		&i.CategoryColor,
	)
	return i, err
}

const listDistinctTransactionMonths = `-- name: ListDistinctTransactionMonths :many
SELECT DISTINCT date_trunc('month', occurred_on)::date AS month
FROM transactions
WHERE user_id = $1
ORDER BY month DESC
`

func (q *Queries) ListDistinctTransactionMonths(ctx context.Context, userID int64) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listDistinctTransactionMonths, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var month pgtype.Date
		if err := rows.Scan(&month); err != nil {
			return nil, err
		}
		items = append(items, month)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsForMonth = `-- name: ListTransactionsForMonth :many
SELECT t.id, t.user_id, t.category_id, t.amount, t.type, t.description, t.occurred_on, t.created_at, t.updated_at, c.slug AS category_slug, c.name AS category_name, c.color AS category_color
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1 AND t.occurred_on >= $2 AND t.occurred_on < $3
  AND ($4::text IS NULL
       OR t.description ILIKE '%' || $4::text || '%'
       OR (c.slug IS NULL AND c.name ILIKE '%' || $4::text || '%')
       OR c.slug = ANY($5::text[]))
  AND ($6::text IS NULL OR t.type = $6::text)
  AND ($7::bigint IS NULL OR t.category_id = $7::bigint)
  AND ($8::bigint IS NULL OR t.amount >= $8::bigint)
  AND ($9::bigint IS NULL OR t.amount <= $9::bigint)
ORDER BY
  CASE WHEN $10::text = 'amount_desc' THEN t.amount END DESC,
  CASE WHEN $10::text = 'amount_asc' THEN t.amount END ASC,
  t.occurred_on DESC, t.id DESC
LIMIT $12 OFFSET $11
`

type ListTransactionsForMonthParams struct {
	UserID       int64       `json:"user_id"`
	OccurredOn   pgtype.Date `json:"occurred_on"`
	OccurredOn_2 pgtype.Date `json:"occurred_on_2"`
	Search       pgtype.Text `json:"search"`
	SearchSlugs  []string    `json:"search_slugs"`
	Type         pgtype.Text `json:"type"`
	CategoryID   pgtype.Int8 `json:"category_id"`
	MinAmount    pgtype.Int8 `json:"min_amount"`
	MaxAmount    pgtype.Int8 `json:"max_amount"`
	Sort         pgtype.Text `json:"sort"`
	Offset       pgtype.Int4 `json:"offset"`
	Limit        pgtype.Int4 `json:"limit"`
}

type ListTransactionsForMonthRow struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	CategoryID    int64              `json:"category_id"`
	Amount        int64              `json:"amount"`
	Type          string             `json:"type"`
	Description   string             `json:"description"`
	OccurredOn    pgtype.Date        `json:"occurred_on"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CategorySlug  pgtype.Text        `json:"category_slug"`
	CategoryName  string             `json:"category_name"`
	CategoryColor string             `json:"category_color"`
}

// ListTransactionsForMonth returns one page of the month's transactions,
// narrowed by whatever the search box and filter panel are asking for. The
// list page is paginated (see pageSize in internal/handlers/req_paging.go), so
// every caller wants a window rather than the whole month; a caller that only
// needs how many there are should use CountTransactionsForMonth instead of
// reading rows it will throw away.
//
// The five filter parameters are all nullable, and a NULL switches its own
// predicate off -- which is why the filters live here rather than in a second
// query: the unfiltered list is just this one with five NULLs, so there is
// only ever one code path to keep in step with CountTransactionsForMonth.
// That matters because the count is what the pager and the count chip are
// built from; a count that did not know about the filters would promise
// pages the list cannot fill.
//
// The search is a case-insensitive substring match, and it covers the category
// as well as the note, because both are on screen in every row: someone who
// can see "Transport" in the list will type it into the search box.
//
// Which is why the category arrives as two predicates rather than one. A
// category the user created shows the name they typed, so the name column is
// what to match -- but only for those, which is what the NULL slug tests. A
// default category shows a label that lives in internal/i18n, keyed by slug,
// and its name column is only ever a fallback; matching it would search
// whatever a migration left there instead of what the row displays. So the
// handler translates the term into the slugs whose labels contain it and
// passes those down, keeping the match on the one thing that identifies a
// default category.
//
// None of this can use an index and none of it needs to: the month window in
// front of it is already covered by idx_transactions_user_id_occurred_on, and
// one person's month is not a large scan.
//
// The order arrives as a sixth nullable parameter rather than as a string
// pasted into the ORDER BY, which is the only way it could be a parameter at
// all: SQL cannot bind a sort column. Each of the two CASEs tests the same
// value against one of the orders the list offers, so exactly one of them
// yields t.amount and the other yields NULL for every row -- and a column
// that is NULL the whole way down ties every row against every other, leaving
// the next term to decide. A NULL parameter, or one naming an order that does
// not exist, therefore falls through both and lands on the date order the
// list has always had, which is also why that pair stays last rather than
// being switched between.
func (q *Queries) ListTransactionsForMonth(ctx context.Context, arg ListTransactionsForMonthParams) ([]ListTransactionsForMonthRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsForMonth,
		arg.UserID,
		arg.OccurredOn,
		arg.OccurredOn_2,
		arg.Search,
		arg.SearchSlugs,
		arg.Type,
		arg.CategoryID,
		arg.MinAmount,
		arg.MaxAmount,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsForMonthRow
	for rows.Next() {
		var i ListTransactionsForMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Type,
			&i.Description,
			&i.OccurredOn,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategorySlug,
			&i.CategoryName,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlyTotals = `-- name: MonthlyTotals :one
SELECT
    COALESCE(SUM(amount) FILTER (WHERE type = 'expense' AND occurred_on >= $2), 0)::bigint AS total_expense,
    COALESCE(SUM(amount) FILTER (WHERE type = 'income' AND occurred_on >= $2), 0)::bigint AS total_income,
    (COALESCE(SUM(amount) FILTER (WHERE type = 'income' AND occurred_on < $2), 0)
      - COALESCE(SUM(amount) FILTER (WHERE type = 'expense' AND occurred_on < $2), 0))::bigint AS carried_over
FROM transactions
WHERE user_id = $1 AND occurred_on < $3
`

type MonthlyTotalsParams struct {
	UserID       int64       `json:"user_id"`
	OccurredOn   pgtype.Date `json:"occurred_on"`
	OccurredOn_2 pgtype.Date `json:"occurred_on_2"`
}

type MonthlyTotalsRow struct {
	TotalExpense int64 `json:"total_expense"`
	TotalIncome  int64 `json:"total_income"`
	CarriedOver  int64 `json:"carried_over"`
}

// MonthlyTotals returns the displayed month's own two totals plus the
// balance carried into it. The carry-in rides along on this query rather
// than getting one of its own because all four callers that build a balance
// already run this one, and a separate query would mean a second round trip
// at each of them.
//
// The outer WHERE therefore reaches back over the user's whole history
// rather than fencing the month on both sides, and each column narrows from
// there: the two month totals re-apply the lower bound in their FILTER,
// while carried_over takes everything strictly before it. Both predicates
// are still covered by idx_transactions_user_id_occurred_on.
//
// The ::bigint on carried_over wraps the whole subtraction rather than each
// operand: sqlc types a bare binary expression as int32, which would overflow
// a balance past 2.1 tỷ đồng.
func (q *Queries) MonthlyTotals(ctx context.Context, arg MonthlyTotalsParams) (MonthlyTotalsRow, error) {
	row := q.db.QueryRow(ctx, monthlyTotals, arg.UserID, arg.OccurredOn, arg.OccurredOn_2)
	var i MonthlyTotalsRow
	err := row.Scan(&i.TotalExpense, &i.TotalIncome, &i.CarriedOver)
	return i, err
}

const monthlyTotalsSeries = `-- name: MonthlyTotalsSeries :many
SELECT
    date_trunc('month', occurred_on)::date AS month,
    COALESCE(SUM(amount) FILTER (WHERE type = 'expense'), 0)::bigint AS total_expense,
    COALESCE(SUM(amount) FILTER (WHERE type = 'income'), 0)::bigint AS total_income
FROM transactions
WHERE user_id = $1 AND occurred_on >= $2 AND occurred_on < $3
GROUP BY month
ORDER BY month
`

type MonthlyTotalsSeriesParams struct {
	UserID       int64       `json:"user_id"`
	OccurredOn   pgtype.Date `json:"occurred_on"`
	OccurredOn_2 pgtype.Date `json:"occurred_on_2"`
}

type MonthlyTotalsSeriesRow struct {
	Month        pgtype.Date `json:"month"`
	TotalExpense int64       `json:"total_expense"`
	TotalIncome  int64       `json:"total_income"`
}

func (q *Queries) MonthlyTotalsSeries(ctx context.Context, arg MonthlyTotalsSeriesParams) ([]MonthlyTotalsSeriesRow, error) {
	rows, err := q.db.Query(ctx, monthlyTotalsSeries, arg.UserID, arg.OccurredOn, arg.OccurredOn_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyTotalsSeriesRow
	for rows.Next() {
		var i MonthlyTotalsSeriesRow
		if err := rows.Scan(&i.Month, &i.TotalExpense, &i.TotalIncome); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignCategoryTransactions = `-- name: ReassignCategoryTransactions :execrows
UPDATE transactions SET category_id = $1
WHERE category_id = $2 AND user_id = $3
`

type ReassignCategoryTransactionsParams struct {
	CategoryID   int64 `json:"category_id"`
	CategoryID_2 int64 `json:"category_id_2"`
	UserID       int64 `json:"user_id"`
}

func (q *Queries) ReassignCategoryTransactions(ctx context.Context, arg ReassignCategoryTransactionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, reassignCategoryTransactions, arg.CategoryID, arg.CategoryID_2, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET category_id = $3, amount = $4, type = $5, description = $6, occurred_on = $7, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, category_id, amount, type, description, occurred_on, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID          int64       `json:"id"`
	UserID      int64       `json:"user_id"`
	CategoryID  int64       `json:"category_id"`
	Amount      int64       `json:"amount"`
	Type        string      `json:"type"`
	Description string      `json:"description"`
	OccurredOn  pgtype.Date `json:"occurred_on"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Type,
		arg.Description,
		arg.OccurredOn,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Type,
		&i.Description,
		&i.OccurredOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
