// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, category_id, amount, type, description, occurred_on)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, category_id, amount, type, description, occurred_on, created_at, updated_at
`

type CreateTransactionParams struct {
	UserID      int64       `json:"user_id"`
	CategoryID  int64       `json:"category_id"`
	Amount      int64       `json:"amount"`
	Type        string      `json:"type"`
	Description string      `json:"description"`
	OccurredOn  pgtype.Date `json:"occurred_on"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Type,
		arg.Description,
		arg.OccurredOn,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Type,
		&i.Description,
		&i.OccurredOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, user_id, category_id, amount, type, description, occurred_on, created_at, updated_at FROM transactions WHERE id = $1 AND user_id = $2
`

type GetTransactionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Type,
		&i.Description,
		&i.OccurredOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactionsForMonth = `-- name: ListTransactionsForMonth :many
SELECT t.id, t.user_id, t.category_id, t.amount, t.type, t.description, t.occurred_on, t.created_at, t.updated_at, c.name AS category_name, c.color AS category_color
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1 AND t.occurred_on >= $2 AND t.occurred_on < $3
ORDER BY t.occurred_on DESC, t.id DESC
`

type ListTransactionsForMonthParams struct {
	UserID       int64       `json:"user_id"`
	OccurredOn   pgtype.Date `json:"occurred_on"`
	OccurredOn_2 pgtype.Date `json:"occurred_on_2"`
}

type ListTransactionsForMonthRow struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	CategoryID    int64              `json:"category_id"`
	Amount        int64              `json:"amount"`
	Type          string             `json:"type"`
	Description   string             `json:"description"`
	OccurredOn    pgtype.Date        `json:"occurred_on"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CategoryName  string             `json:"category_name"`
	CategoryColor string             `json:"category_color"`
}

func (q *Queries) ListTransactionsForMonth(ctx context.Context, arg ListTransactionsForMonthParams) ([]ListTransactionsForMonthRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsForMonth, arg.UserID, arg.OccurredOn, arg.OccurredOn_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsForMonthRow
	for rows.Next() {
		var i ListTransactionsForMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Type,
			&i.Description,
			&i.OccurredOn,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET category_id = $3, amount = $4, type = $5, description = $6, occurred_on = $7, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, category_id, amount, type, description, occurred_on, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID          int64       `json:"id"`
	UserID      int64       `json:"user_id"`
	CategoryID  int64       `json:"category_id"`
	Amount      int64       `json:"amount"`
	Type        string      `json:"type"`
	Description string      `json:"description"`
	OccurredOn  pgtype.Date `json:"occurred_on"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Type,
		arg.Description,
		arg.OccurredOn,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Type,
		&i.Description,
		&i.OccurredOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
