// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearFailedLogins = `-- name: ClearFailedLogins :exec
UPDATE users SET failed_login_attempts = 0, locked_until = NULL WHERE id = $1
`

// ClearFailedLogins wipes the throttle state, called both after a correct
// password and after a password reset -- the reset is what lets a locked-out
// owner back in without waiting the window out.
func (q *Queries) ClearFailedLogins(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearFailedLogins, id)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, username)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, name, created_at, theme, username, failed_login_attempts, locked_until
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
	Username     string `json:"username"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Username,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.Theme,
		&i.Username,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, created_at, theme, username, failed_login_attempts, locked_until FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.Theme,
		&i.Username,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, created_at, theme, username, failed_login_attempts, locked_until FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.Theme,
		&i.Username,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const recordFailedLogin = `-- name: RecordFailedLogin :one
UPDATE users
SET failed_login_attempts = failed_login_attempts + 1,
    locked_until = CASE
        WHEN failed_login_attempts + 1 >= $1::int THEN $2::timestamptz
        ELSE locked_until
    END
WHERE id = $3
RETURNING failed_login_attempts, locked_until
`

type RecordFailedLoginParams struct {
	MaxAttempts int32              `json:"max_attempts"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
	ID          int64              `json:"id"`
}

type RecordFailedLoginRow struct {
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
}

// RecordFailedLogin counts one wrong password and, on the attempt that
// reaches max_attempts, stamps the lock. Counting and locking happen in the
// one statement so two simultaneous guesses can't both read the same count
// and each write back the same +1 -- a read-modify-write in Go would let a
// parallel flood spend far more than max_attempts guesses.
func (q *Queries) RecordFailedLogin(ctx context.Context, arg RecordFailedLoginParams) (RecordFailedLoginRow, error) {
	row := q.db.QueryRow(ctx, recordFailedLogin, arg.MaxAttempts, arg.LockedUntil, arg.ID)
	var i RecordFailedLoginRow
	err := row.Scan(&i.FailedLoginAttempts, &i.LockedUntil)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users SET email = $2 WHERE id = $1
`

type UpdateUserEmailParams struct {
	ID    int64  `json:"id"`
	Email string `json:"email"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.ID, arg.Email)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users SET name = $2, username = $3 WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Username string `json:"username"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile, arg.ID, arg.Name, arg.Username)
	return err
}

const updateUserTheme = `-- name: UpdateUserTheme :exec
UPDATE users SET theme = $2 WHERE id = $1
`

type UpdateUserThemeParams struct {
	ID    int64  `json:"id"`
	Theme string `json:"theme"`
}

func (q *Queries) UpdateUserTheme(ctx context.Context, arg UpdateUserThemeParams) error {
	_, err := q.db.Exec(ctx, updateUserTheme, arg.ID, arg.Theme)
	return err
}
